### ISSUE TITLE
404 - page not found

### ISSUE THREAD

**Issue by c0d33ngr** [badging/badging#79]
Under the heading ```How does DEI Project Badging work?``` a link that should lead to how to create ```DEI.md``` and what it entails is broken.

**Comment by kaxada** [comment]
@c0d33ngr  we have mostly moved all the badging work from `All In` to this repo and https://github.com/badging/BadgingAPI. If you are looking for references on project badging consider going to https://badging.chaoss.community/project-badging.

Please let me know where you are trying to access the link from so that we can update it

**Comment by c0d33ngr** [comment]
Hi @kaxada it's the ```README.md``` of this repo. The first bullet point of the heading ```How does DEI Project Badging work?```. The link **here** is pointing to in the readme is broken

**Comment by kaxada** [comment]
@c0d33ngr thank you for the vigilance. this has been fixed and closed.
